name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: oceanbase/setup-oceanbase-ce@main
      - name: Connect to OceanBase container
        run: docker exec oceanbase-ce obclient -h127.0.0.1 -P2881 -uroot -e 'select version()'
